name: Go CI & Docker Build to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: GCP_SA_KEY
    env:
      GCR_JSON_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
    - name: Checkout repozytorium
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use GCR
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ${{ env.GOPATH }}/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Pobierz zależności
      run: go mod download

    - name: Uruchom testy
      run: go test ./...

    - name: Zbuduj aplikację
      run: go build -o go-ping .

    - name: Zbuduj obraz Dockerowy
      run: docker build -t go-ping:latest .
    
    - name: Tagowanie obrazu dla Artifact Registry
      run: docker tag go-ping:latest europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-containers/go-ping:latest

    - name: Wypchnięcie obrazu do Artifact Registry
      run: docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-containers/go-ping:latest
    